import type { Plan, Spec } from './schemas.js';

/** Max plan regenerations from change requests before asking the human to decide. */
export const PLAN_REVISION_CAP = 3;

export interface PlanMeta {
  issueNumber: number;
  title: string;
}

function bulletList(items: string[], emptyText = '_None._'): string {
  if (items.length === 0) return emptyText;
  return items.map((i) => `- ${i}`).join('\n');
}

/** The committed `plan.md` body — the technical source of truth re-read by Phase 8. */
export function renderPlanMarkdown(plan: Plan, meta: PlanMeta): string {
  const files = plan.affectedFiles
    .map((f) => `- \`${f.path}\` **(${f.change})** — ${f.reason}`)
    .join('\n');

  return [
    `# Plan — Issue #${meta.issueNumber}: ${meta.title}`,
    '',
    '> Generated by Tsukinome. The technical blueprint for the work, approved before any code.',
    '',
    '## Summary',
    '',
    plan.summary,
    '',
    '## Approach',
    '',
    plan.approach,
    '',
    '## Affected Files',
    '',
    files || '_None._',
    '',
    '## Contracts',
    '',
    bulletList(plan.contracts),
    '',
    '## Data Changes',
    '',
    bulletList(plan.dataChanges),
    '',
    '## Test Strategy',
    '',
    bulletList(plan.testStrategy),
    '',
  ].join('\n');
}

/** The plan-gate comment: spec + plan together, with the approval instructions. */
export function renderPlanGateComment(spec: Spec, plan: Plan): string {
  const files = plan.affectedFiles.map((f) => `- \`${f.path}\` (${f.change})`).join('\n');
  return [
    '🧭 **Plan ready for review.** Here is the spec and the technical plan together — committed to ' +
      '`.tsukinome/` on the working branch.',
    '',
    '## Spec',
    '',
    spec.summary,
    '',
    `**Acceptance criteria:** ${spec.acceptanceCriteria.length} · **Non-goals:** ${spec.nonGoals.length}`,
    '',
    '## Plan',
    '',
    plan.summary,
    '',
    plan.approach,
    '',
    '**Affected files:**',
    '',
    files || '_None._',
    '',
    '**Test strategy:**',
    '',
    bulletList(plan.testStrategy),
    '',
    '---',
    '',
    'Reply **`/approve`** to start implementation, **`/abort`** to close this out, or describe the ' +
      'changes you want and I’ll revise the plan.',
  ].join('\n');
}

export function renderPlanApprovedComment(): string {
  return '✅ **Plan approved.** Starting implementation — I’ll work each task test-first.';
}

export function renderPlanAbortedComment(): string {
  return '🛑 **Aborted.** I’ve closed this run and made no further changes.';
}

export function renderDorNotReadyComment(reasons: string[]): string {
  return [
    '⏳ **Not ready to plan yet.** Before I can draft a technical plan, this needs:',
    '',
    reasons.map((r) => `- ${r}`).join('\n'),
  ].join('\n');
}

export function renderPlanRevisionCapComment(): string {
  return (
    `🔁 **That’s ${PLAN_REVISION_CAP} rounds of plan revisions.** To keep things moving, please ` +
    'reply **`/approve`** to proceed with the current plan or **`/abort`** to stop — I won’t auto-revise further.'
  );
}

export interface DorResult {
  ready: boolean;
  reasons: string[];
}

/**
 * Definition of Ready: the mechanical gate the orchestrator uses to refuse advancing to the
 * plan gate. Open questions are the critical check (they must have been resolved by the
 * clarification gate); criteria-testable and non-goals-stated round it out.
 */
export function definitionOfReady(spec: Spec): DorResult {
  const reasons: string[] = [];
  if (spec.openQuestions.length > 0) reasons.push('open clarification questions remain');
  if (spec.acceptanceCriteria.length === 0) reasons.push('no testable acceptance criteria');
  if (spec.nonGoals.length === 0) reasons.push('non-goals are not stated');
  return { ready: reasons.length === 0, reasons };
}

export type PlanDecision = 'approve' | 'abort' | 'changes';

/** Parse a maintainer's gate comment. `/approve` and `/abort` win; anything else is a change request. */
export function parsePlanDecision(body: string): PlanDecision {
  if (/\/approve\b/i.test(body)) return 'approve';
  if (/\/abort\b/i.test(body)) return 'abort';
  return 'changes';
}
