import type { Plan, Review, Spec } from './schemas.js';

export interface PrMeta {
  title: string;
}

function bulletList(items: string[], emptyText = '_None._'): string {
  if (items.length === 0) return emptyText;
  return items.map((i) => `- ${i}`).join('\n');
}

const VERDICT_LABEL: Record<Review['verdict'], string> = {
  approve: '✅ Approve',
  request_changes: '🔧 Changes suggested',
};

export function renderPrTitle(meta: PrMeta, issueNumber: number): string {
  return `${meta.title} (#${issueNumber})`;
}

function renderFindings(review: Review): string {
  if (review.findings.length === 0) return '_No findings._';
  return review.findings
    .map((f) => `- **${f.severity}**${f.file ? ` \`${f.file}\`` : ''}: ${f.note}`)
    .join('\n');
}

/** The PR body — the audit trail: spec, plan, assumptions, self-review, cost, and the issue link. */
export function renderPrBody(input: {
  spec: Spec;
  plan: Plan;
  review: Review;
  issueNumber: number;
  costSummary: string;
}): string {
  const { spec, plan, review, issueNumber, costSummary } = input;
  const files = plan.affectedFiles.map((f) => `- \`${f.path}\` (${f.change})`).join('\n');

  return [
    `> Generated by Tsukinome. Resolves #${issueNumber}.`,
    '',
    '## Spec',
    '',
    spec.summary,
    '',
    `**Acceptance criteria:** ${spec.acceptanceCriteria.length} · **Non-goals:** ${spec.nonGoals.length}`,
    '',
    '## Plan',
    '',
    plan.summary,
    '',
    plan.approach,
    '',
    '**Affected files:**',
    '',
    files || '_None._',
    '',
    '## Assumptions',
    '',
    bulletList(spec.assumptions, '_None — the issue was fully specified._'),
    '',
    '## Self-review',
    '',
    `**Verdict:** ${VERDICT_LABEL[review.verdict]}`,
    '',
    review.summary,
    '',
    renderFindings(review),
    '',
    '## Cost',
    '',
    costSummary,
    '',
    '---',
    '',
    'The spec, plan, and a test-first commit per task are on this branch. Review and merge, or comment to request changes.',
  ].join('\n');
}

/** Posted on the issue once the PR is open — the human-facing pointer + verdict + run cost. */
export function renderReviewedComment(prUrl: string, review: Review, costSummary: string): string {
  return (
    `🔀 **Pull request opened:** ${prUrl}\n\n` +
    `Self-review verdict: ${VERDICT_LABEL[review.verdict]}. ${review.summary}\n\n` +
    costSummary
  );
}
